### ISSUE TITLE
Carnot returns "API returned error 401, Validation error - check your credentials!"

### ISSUE THREAD

**Issue by Alexikik** [MTrab/energidataservice#577]
### Describe the issue

The Carnot extension doesn't work. I can see in the logs that it returns "API returned error 401, Validation error - check your credentials!"

The credentials has been triple checked. Seems like the wrong credentials are sent or that Carnot has a problem

### What version of Home Assistant Core has the issue?

core-2024.8.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[Home Assistant Energidataservice Log Aug 30 2024.log](https://github.com/user-attachments/files/16814636/Home.Assistant.Energidataservice.Log.Aug.30.2024.log)

**Comment by MTrab** [comment]
No problems here, data are fetched as supposed. 
Guess you are entering something incorrect

**Comment by zaughon** [comment]
I have been having similar issues, but i may have figured out what caused it (at least for me).
I set it up yesterday and it fetched data for yesterday and today just fine. I ended up removing the integration and setting it up again because i wanted to set it up twice, one including tariffs, and one excluding it.
Since then, i've been consistently getting the same error in the logs. I attempted to delete my API-key in carnot and request a new one and set that up in HA, but the errors stayed, and when i checked today it was missing estimates for tomorrow.

I removed both those integrations from yesterday and set up a new one, again with a completely new API key, and it seems to have added stats for tomorrow correctly, but i still saw bursts of this error.

This made me attempt this: 
https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging

Looking at the debug log, it was attempting to fetch data using several of my old keys. My guess is the integration entries i deleted were not fully deleted, and were still running in the background even though they didn't exist anymore, and these are the ones causing the errors. 
This made me delete my API key in Carnot, then delete all integrations for this, and finally reboot HA. This seemed to stop the errors.

I've now set up both integration entries again using a newly generated API-key, and so far, both integration entries have updated from Carnot several times, and not a single API error in the logs yet.
Let's see tomorrow if it manages to automatically fetch data for thursday or if something is failing again.

**Comment by zaughon** [comment]
I forgot to update, but there's been no further validation errors for me.
If you're still having issues, try removing all integrations, then restart HA, and afterwards set them up again.
They seem to keep running in the background if you just remove them. I'm not sure if that's a bug here or just a HA "feature".

**Comment by TroelsDane** [comment]
My carnot forecast is not working either



I tried uninstall, restart and reinstall

I wanted to double check my carnot api key was not expired, but I can't login to carnot

Maybe they have issues?

**Comment by KennethLavrsen** [comment]
I am having the error now. 

Logger: custom_components.energidataservice.connectors.nordpool
Source: custom_components/energidataservice/connectors/nordpool/__init__.py:105
integration: Energi Data Service ([documentation](https://github.com/MTrab/energidataservice/blob/master/README.md), [issues](https://github.com/MTrab/energidataservice/issues))
First occurred: 09:28:51 (6 occurrences)
Last logged: 09:28:55

API returned error 404

**Comment by MTrab** [comment]
That is Norpool having an error - not Carnot

**Comment by MTrab** [comment]
If this is still an issue, please contact Carnot as it has to be on their side. It works for almost everyone else
