### ISSUE TITLE
[FR]: Pull additional charges from Energidataservice API

### ISSUE THREAD

**Issue by MTrab** [MTrab/energidataservice#79]
Pull additional charges from https://www.energidataservice.dk/tso-electricity/DatahubPricelist

**Comment by luckow** [comment]
This will be really useful as the charges now vary a lot over the day. I hope you'll get the time to do it some day.

**Comment by wizzd44** [comment]
Yes ... bumping this one. 
(and Thanks for developing the integration :) )

**Comment by MTrab** [comment]
No need to bump anything. Having a hard time understanding the codes, and as long as I can't get the grip of what is what in the data, this will not happen.

**Comment by wizzd44** [comment]
didn't really mean bump ... more like "supporting" this one :)

**Comment by smulle48** [comment]
> No need to bump anything. Having a hard time understanding the codes, and as long as I can't get the grip of what is what in the data, this will not happen.

If you take a look at this:

https://api.energidataservice.dk/dataset/DatahubPricelist?offset=0&start=2022-10-22T00:00&end=2022-10-23T00:00&filter=%7B%22ChargeOwner%22:[%22N1%20A/S%20-%20344%22],%22ChargeTypeCode%22:[%22T-C-F-T-TD%22,%22T-C-RA-TD%22]%7D&sort=ValidFrom%20DESC&timezone=dk

My provider is N1 A/S (old Evonet) so my GLN Number is: 5790000611003

The GLN Number is unique to the specific provider. Even N1 got separate GLN numbers for each of their sub networks (N1, Old Evonet, N1 Randers, etc.)

Depending on the provider, you can have discount or not. In my case I have discount, until 1/1-2023, where all N1 providers merge under 1 GLN number without any discount at all.

If we don't take discount into the equation, the next thing you need is the ChargeTypeCode. In my case it's: T-C-F-T-TD

The Price1 to Price24 is the price ex vat for each hour. Even though the online version round the numbers up and down, the raw data still contain all the decimals.

So if we take this:

https://api.energidataservice.dk/dataset/DatahubPricelist?offset=0&start=2022-10-22T00:00&end=2022-10-23T00:00&filter=%7B%22GLN_Number%22:[%225790000611003%22],%22ChargeTypeCode%22:[%22T-C-F-T-TD%22]%7D&sort=ValidFrom%20DESC&timezone=dk

Then, what the user needs to configure it the GLN Number and the ChargeTypeCode.

You then "just" need to extract the value from each timeslot and add it as an extra cost :-D

I hope it makes sense

**Comment by cokeman0** [comment]
I just took a look at my setup, and here you need 2 data sets to get the right data.

We have a local provider "Kongerslev EL-NET A/S", that get the "juice" from N1, så we need to add up both.

https://api.energidataservice.dk/dataset/DatahubPricelist?offset=0&start=2023-01-31T00:00&end=2023-02-05T00:00&filter=%7B%22GLN_Number%22:[%225790002502699%22]%7D&sort=ValidFrom%20DESC&timezone=dk

"Kongerslev el-net" add 0.12kr on top of the N1 Nettarif C time (Price confirmed from el-net kongerslev homepage)

p.s. i'm a member ont the board of directores in that company.

**Comment by adamhassel** [comment]
Hey, I've implemented this in my home brew solution over here: https://github.com/adamhassel/power/
I'm using it to combine eloverblik.dk (which has the regular consumption data two-ish days delayed, but also has an endpoint to get your personal tariffs) with energidataservice, in order to display the grand total per-kWh price on my home brew eink dashboard.

You'll need an API-key and the measurement point ID from eloverblik.dk, which required NemID/MitID, but other than that, it's pretty straight forward. The main challenge is the "Position" concept, which is basically how a given tariff is split over a given day. This is also what controls the differing tariffs during a day. You'll notice how some of these tariffs have one entry in the Position slice/array (meaning one price for the whole day) or 24 (meaning per-hour).

The only thing that's not implemented (beacuse it doesn't apply to me, and it's a personal use project anyway) is support for multiple meters. This is somewhat complicated, because some installations will have several meters, and tariffs may differ on them. For example, you might have a meter that only handles production (solar cells), and another that's connected to a business account. These may or may not be "child meters" of a main meter, and I've not explored how that affects the calculation of the grand total. Like, does that mean that the main meter's tariffs are a grand total, or are you supposed to add for all child meters? :shrug: ). I don't have multiple meters, so I've not had motivation or even anywhere to test, so ... ;)

Either way, feel free to draw inspiration from it. The data handling of the tariffs is over in https://github.com/adamhassel/power/blob/main/repos/eloverblik/eloverblik.go

**Comment by cnrd** [comment]
Here is a pretty rough connector implementing fetching raw data from eloverblik

```python
import json
import time
from logging import getLogger

from aiohttp import ClientSession

_LOGGER = getLogger(__name__)

BASE_URL = "https://api.eloverblik.dk/CustomerApi/api"
TOKEN_API = "/token"
METERINGPOINTS_API = "/meteringpoints/meteringpoint/getcharges"

FETCH_TIME = 60 * 60 * 12


class Connector:

    def __init__(self, refresh_token: str, client: ClientSession):
        self._refresh_token = refresh_token
        self._client = client

        self._data_token = None
        self._last_fetch_data_token = 0

        self._raw_result = None

    async def _fetch_data_token(self) -> None:
        now = time.time()
        if (now - self._last_fetch_data_token) > FETCH_TIME:
            url = BASE_URL + TOKEN_API
            headers = {"Authorization": "Bearer " + self._refresh_token}
            resp = await self._client.get(url, headers=headers)

            if resp.status == 200:
                res = await resp.json()
                self._data_token = res["result"]
            else:
                _LOGGER.error("fetch_token: " + str(resp.status))

            self._last_fetch_data_token = now

    async def fetch_charges(self, metering_point_ids: list) -> None:
        await self._fetch_data_token()

        url = BASE_URL + METERINGPOINTS_API
        data = self._build_data(metering_point_ids)
        headers = {"Authorization": "Bearer " + self._data_token,
                   "Content-Type": "application/json",
                   "Content-Length": str(len(data))}

        _LOGGER.debug(data)

        resp = await self._client.post(url, data=data, headers=headers)

        if resp.status == 200:
            self._raw_result = await resp.json()
        else:
            _LOGGER.error("fetch_data: " + str(resp.status))

    def _build_data(self, metering_point_ids: list) -> str:
        data = {"meteringPoints": {"meteringPoint": metering_point_ids}}

        return json.dumps(data)

    def get_raw_result(self):
        return self._raw_result

```
